### ISSUE TITLE
Nearly continuous "Syncronizing Block Infomation"

### ISSUE THREAD

**Issue by madfusker** [jlesage/docker-crashplan-pro#337]
-QNAP, container in docker
-v 8.8.1 as of yesterday

This has been going on for a while now, even in the previous version and I am not sure how to fix it.  CP will synchronize block information up to 100% and fully complete, and then all things look normal, but the next time I look at it it's syncing block info again.  Seems like it's doing it almost all the time.  It backs things up during the process once in a while, but it shouldn't be doing this all the time.  I used to see it after upgrading, or maybe once a month.  After updating to 8.8.1 last night, synced block and everything was idle waiting for backup.  A few hours later it's syncing block again and will take most of the day.

Does anyone have some ideas why it's constantly doing this? The console log doesn't really show anything except the backups are still completing.

Thanks.

**Comment by jlesage** [comment]
In CrashPlan, does Tools->History showing something interesting ?

**Comment by axemanozh** [comment]
I'm seeing similar behavior, also on QNAP and the 8.8.1 image. Crashplan appears to be continuously trying to reupload data that's already been uploaded to CrashPlan Online.

![image](https://user-images.githubusercontent.com/59229270/146647979-29c8fe65-1a39-4db3-95aa-516b46247281.png)

The log doesn't appear to show anything particular noteworthy, other than that it's trying to upload files.

12/16/21 05:49PM Download of upgrade failed - version 1525200006881, verification failed.
12/16/21 05:49PM Unable to apply upgrade(s), retrying in one hour
12/16/21 05:53PM Code42 started, version 8.8.1, GUID 923031853398292863
12/16/21 05:53PM [PRO Online Backup Set] Scanning for files to back up
12/16/21 05:54PM [PRO Online Backup Set] Scanning for files completed in 1 minute: 37,287 files (5.30TB) found
12/17/21 02:52AM [PRO Online Backup Set] Starting backup to CrashPlan PRO Online: 17,983 files (5.30TB) to back up
12/17/21 02:52AM [PRO Online Backup Set] Scanning for files to back up
12/17/21 02:52AM [PRO Online Backup Set] Stopped backup to CrashPlan PRO Online in 0h:00m:01s: 0 files (0MB) backed up, 0MB encrypted and sent
12/17/21 02:52AM  - Reason for stopping backup: Full filesystem scan started.
12/17/21 02:52AM [PRO Online Backup Set] Starting backup to CrashPlan PRO Online: 207 files (620.60GB) to back up
12/17/21 02:53AM [PRO Online Backup Set] Scanning for files completed in < 1 minute: 37,289 files (5.30TB) found
12/17/21 03:00AM [PRO Online Backup Set] Scanning for files to back up
12/17/21 03:00AM [PRO Online Backup Set] Stopped backup to CrashPlan PRO Online in 0h:07m:45s: 1 file (66.60MB) backed up, 66.10MB encrypted and sent (Effective rate: 1.3Mbps)
12/17/21 03:00AM  - Reason for stopping backup: Full filesystem scan started.
12/17/21 03:01AM [PRO Online Backup Set] Starting backup to CrashPlan PRO Online: 7,868 files (737.40GB) to back up
12/17/21 03:01AM [PRO Online Backup Set] Scanning for files completed in < 1 minute: 37,289 files (5.30TB) found
12/17/21 11:18AM [PRO Online Backup Set] Scanning for files to back up
12/17/21 11:18AM [PRO Online Backup Set] Stopped backup to CrashPlan PRO Online in 8h:17m:01s: 32 files (5.90GB) backed up, 3.20GB encrypted and sent (Effective rate: 942.2Mbps)
12/17/21 11:18AM  - Reason for stopping backup: Full filesystem scan started.
12/17/21 11:18AM [PRO Online Backup Set] Starting backup to CrashPlan PRO Online: 3,769 files (640.50GB) to back up
12/17/21 11:20AM [PRO Online Backup Set] Scanning for files completed in 2 minutes: 37,289 files (5.30TB) found
12/17/21 11:37PM [PRO Online Backup Set] Completed backup to CrashPlan PRO Online in 12h:19m:02s: 1 file (3GB) backed up, 1KB encrypted and sent (Effective rate: 935.9Mbps)
12/18/21 03:00AM [PRO Online Backup Set] Scanning for files to back up
12/18/21 03:01AM [PRO Online Backup Set] Scanning for files completed in 2 minutes: 37,290 files (5.30TB) found
12/18/21 11:08AM [PRO Online Backup Set] Backup to CrashPlan PRO Online will take priority until complete (up to 24 hours)
12/18/21 11:08AM [PRO Online Backup Set] Starting backup to CrashPlan PRO Online: 14,006 files (5.30TB) to back up


I'm guessing there might be a bug in the software, which is CrashPlan pulled the 8.8 software after only being released for a few hours and then took a month to reissue it as 8.8.1?

**Comment by madfusker** [comment]
> In CrashPlan, does Tools->History showing something interesting ?

No, nothing at all.  And to be clear, this was happening before the v8.8.1 release in which I was running v8.7.1.  I was just being patient and hoping v8.8.1 would fix the issue when it came out.

You can see below that at 1:19am it was showing all backed up and waiting for changes.  But this morning at 10:25am I am seeing that it is syncing block information yet again and is 55% complete.  I will post back what happens tonight and see if it start another block sync.

I 12/17/21 08:03PM 42 7d98d2f68672cead9a5aa9ceb287a19c 0 /share/Apps/Drivers/Intel X520A/DOCS/QUICK/FRA/license.htm (26984) [7,0,26984,0,0,2,2]
I 12/17/21 08:03PM 42 cbee372ddb29f1f257982f2a594360f2 0 /share/Apps/Drivers/Intel X520A/DOCS/i40evf_to_iavf_transition.pdf (123170) [4,0,123170,0,0,545,545]
I 12/17/21 08:03PM 42 df9e53ccf544fadb4a4f3c3a40089881 0 /share/Apps/Drivers/Intel X520A/DOCS/style.css (2649) [0,1,0,0,0,0,0]
I 12/17/21 08:03PM 42 57d83854110b7dcd3159259bcb9edeb5 0 /share/Apps/Drivers/Intel X520A/DOCS/note.gif (1008) [0,1,0,0,0,0,0]
I 12/17/21 08:03PM 42 [Core] Completed backup to CrashPlan Central in 0h:02m:54s: 124 files (144.70MB) backed up, 30.60MB encrypted and sent @ 3.7Mbps (Effective rate: 9.5Mbps) [476,108,29096386,0,0,255506,255435]
I 12/17/21 08:03PM 42  - Unable to backup 1 file (next attempt within 60 minutes)
W 12/17/21 08:03PM 42  - /share/Logs/messages
I 12/17/21 09:03PM 42 [Core] Starting backup to CrashPlan Central: 1 file (57.70MB) to back up
I 12/17/21 09:04PM 42 [Core] Completed backup to CrashPlan Central in 0h:00m:11s: 0 files (116.40MB) backed up, 204.60KB encrypted and sent @ 302.2Kbps (Effective rate: 92.8Mbps) [0,0,0,0,0,0,0]
I 12/17/21 09:04PM 42  - Unable to backup 1 file (next attempt within 60 minutes)
W 12/17/21 09:04PM 42  - /share/Logs/messages
I 12/17/21 10:04PM 42 [Core] Starting backup to CrashPlan Central: 1 file (59.30MB) to back up
I 12/17/21 10:04PM 42 [Core] Completed backup to CrashPlan Central in 0h:00m:10s: 0 files (119.50MB) backed up, 166.40KB encrypted and sent @ 281Kbps [0,0,0,0,0,0,0]
I 12/17/21 10:04PM 42  - Unable to backup 1 file (next attempt within 60 minutes)
W 12/17/21 10:04PM 42  - /share/Logs/messages
I 12/17/21 11:05PM 42 [Core] Starting backup to CrashPlan Central: 1 file (60.90MB) to back up
I 12/17/21 11:05PM 42 [Core] Completed backup to CrashPlan Central in 0h:00m:10s: 0 files (122.70MB) backed up, 182.80KB encrypted and sent @ 336Kbps [0,0,0,0,0,0,0]
I 12/17/21 11:05PM 42  - Unable to backup 1 file (next attempt within 60 minutes)
W 12/17/21 11:05PM 42  - /share/Logs/messages
I 12/17/21 11:46PM 42 [Pictures.and.Videos] Starting backup to CrashPlan Central: 1 file (191.40KB) to back up
I 12/17/21 11:46PM 42 d56719d9c6a1390fd83c4983a72c9a1d 0 /share/Pictures/Screenshot 2021-12-17 174626.png (191359) [6,0,191359,0,0,857,857]
I 12/17/21 11:46PM 42 [Pictures.and.Videos] Completed backup to CrashPlan Central in 0h:00m:05s: 1 file (191.40KB) backed up, 176.90KB encrypted and sent @ 1.8Kbps [6,0,191359,0,0,857,857]
I 12/18/21 12:05AM 42 [Core] Starting backup to CrashPlan Central: 1 file (62.30MB) to back up
I 12/18/21 12:05AM 42 [Core] Completed backup to CrashPlan Central in 0h:00m:09s: 0 files (125.40MB) backed up, 144.90KB encrypted and sent [0,0,0,0,0,0,0]
I 12/18/21 12:05AM 42  - Unable to backup 1 file (next attempt within 60 minutes)
W 12/18/21 12:05AM 42  - /share/Logs/messages
I 12/18/21 01:06AM 42 [Core] Starting backup to CrashPlan Central: 15,911 files (84.30GB) to back up
I 12/18/21 01:06AM 42 cb3c2ba67cad02a3daa756bc5e191ebb 1 /share/Apps/iperf-3.1.3-win64
I 12/18/21 01:06AM 42 a32d072874c9723b0a965902ba65296f 1 /share/Apps/Drivers
I 12/18/21 01:19AM 42 [Core] Completed backup to CrashPlan Central in 0h:13m:22s: 2 files (128.10MB) backed up, 146.80KB encrypted and sent (Effective rate: 968.5Mbps) [0,0,0,0,0,0,0]
I 12/18/21 01:19AM 42  - Unable to backup 1 file (next attempt within 60 minutes)
W 12/18/21 01:19AM 42  - /share/Logs/messages


![image](https://user-images.githubusercontent.com/39440750/146648616-dc8be8d7-112b-4ca7-8072-a3e55e4628ad.png)

**Comment by madfusker** [comment]
Yep... Started a full block sync again this morning.

@jlesage before contacting support, should I just delete ALL local files and restart the container?  Technically speaking, shouldn't I be able to delete ALL files including the conf folder, then adopt it like a new machine?  Or how would you approach this and what would you delete to refresh it?  If this doesn't work then I would know for sure that I need to contact support.

![image](https://user-images.githubusercontent.com/39440750/146682571-c58c4cf1-ae95-4051-8206-5ba0a2113c67.png)

**Comment by jlesage** [comment]
I've seen a similar problem, where the "synchronizing block information" phase would not finish and would restart continually.  According to support team, the issue was caused by some maintenance done on CrashPlan's servers.  The instruction given by support was to deauthorize the device (or stop the container) for a couple of days, until the maintenance completes.

Also, what is the size of your backup?  And what memory limit did you set (the `CRASHPLAN_SRV_MAX_MEM` environment variable) ?  You should make sure to give enough memory by following recommendations (1GB or memory per TB or data).

Finally, erasing the config directory and restarting the container will for sure restart everything from scratch.  Depending on the size of your backup, this may not be an option.  And if the issue is on CrashPlan side, this will probably not help.  This will also create another device in your account, so make sure to login on CrashPlan website and remove the old one, else you will be charged for 2 devices.

So I think your best option may be to contact support.  You will know if the problem is on their side.  As usual, just don't say you are running CrashPlan as a Docker container and they will happily help you :)

**Comment by jlesage** [comment]
@axemanozh, messages might be confusing.  They might suggest that data is re-uploaded, but if data already exists in cloud, it won't.  Look at the "effective rate": a big value means that data has not been re-uploaded.

**Comment by axemanozh** [comment]
> @axemanozh, messages might be confusing. They might suggest that data is re-uploaded, but if data already exists in cloud, it won't. Look at the "effective rate": a big value means that data has not been re-uploaded.

Thanks, @jlesage! I understand that it’s not actually re-uploading all of my data (it took literally about a year to upload 5 TB during my initial upload!). Just bothers my OCD that the UI is continually cycling through that. It is otherwise working normally, including uploading new files I place into my directories that aren’t already uploaded to CrashPlan Online. I guess I’ll have to reach out to support, as well.

**Comment by madfusker** [comment]
> Also, what is the size of your backup? And what memory limit did you set (the `CRASHPLAN_SRV_MAX_MEM` environment variable) ? You should make sure to give enough memory by following recommendations (1GB or memory per TB or data).

Backup is about 2.5TB.  Memory is 16GB in the container and the NAS has 64GB total.

```
docker run --restart unless-stopped -d \
	--name=crashplan-pro \
	--restart=always \
	-e USER_ID=0 \
	-e GROUP_ID=0 \
	-p 5800:5800 \
	-e TZ=America/Chicago \
	-e CRASHPLAN_SRV_MAX_MEM=16384M \
	-v /share/Docker/appdata/crashplan-pro:/config:rw \
	-v /share/CACHEDEV1_DATA/Docker:/share/Docker:ro \
	-v /share/CACHEDEV1_DATA/Logs:/share/Logs:ro \
	-v /share/CE_CACHEDEV2_DATA/Docs.Andrew:/share/Docs:ro \
	-v /share/CACHEDEV3_DATA/Movies:/share/Movies:ro \
	-v /share/CACHEDEV3_DATA/Music:/share/Music:ro \
	-v /share/CACHEDEV3_DATA/Music.HiRes:/share/Music.HiRes:ro \
	-v /share/CACHEDEV3_DATA/Pictures:/share/Pictures:ro \
	jlesage/crashplan-pro
```

**Comment by uberwrensch** [comment]
FWIW I had very similar sounding if not the same endless loop synchronizing within few weeks. I didn't wipe out the entire config, but did more or less everything short of it:
- stopped, removed container
- manually rm'd cache items
- in UI I selected/de-selected a few small files

It's now been good for the past week. Good luck.

**Comment by madfusker** [comment]
> FWIW I had very similar sounding if not the same endless loop synchronizing within few weeks.

Tried your method and it's now syncing back up.  This method did trigger that an upgrade is needed again and I am on 8.8.1.33.  Do you suppose there was an issue with the last version they had to roll another so quickly?

![image](https://user-images.githubusercontent.com/39440750/146834779-71268305-c382-4b5b-a2d3-16cc39465dba.png)

**Comment by jlesage** [comment]
Yes, there was another update.  I just pushed a new image.  Hope it will help with your issue.

**Comment by halteach** [comment]
> 

where are the cache items?

**Comment by jlesage** [comment]
You can refer to instructions at https://github.com/jlesage/docker-crashplan-pro#device-status-is-waiting-for-connection to clear the cache.

**Comment by madfusker** [comment]
> Yes, there was another update. I just pushed a new image. Hope it will help with your issue.

Updated and still getting the continuous block sync even with clearing the cache folder out.  I have NOT tried to fully kill the computer and readopt yet.  I also see that it does fully upload changed files in-between full block syncs which isn't the end of the world, so maybe I will just let it do that for a while and see if it eventually sorts itself out.

**Comment by axemanozh** [comment]
> > Yes, there was another update. I just pushed a new image. Hope it will help with your issue.
> 
> Updated and still getting the continuous block sync even with clearing the cache folder out. I have NOT tried to fully kill the computer and readopt yet. I also see that it does fully upload changed files in-between full block syncs which isn't the end of the world, so maybe I will just let it do that for a while and see if it eventually sorts itself out.

This is where I'm at, as well. Seems like enough other people are having the same or similar problems that it must be something on CrashPlan's end. I've been busy with work and haven't had a chance to submit a ticket with Code42 yet but as long as my data is being synced and backed up, I guess I can live with the UI cycling through that for now.

**Comment by halteach** [comment]
So I don't think this is the same thing but, I'm checking.  Since the update to 8.8.1, when a scan is run it finds new files but it also includes about 24,000 files that haven't changed (see screenshot).  It uploads the new files but, then just goes through what must a check of the other files against what is in the CrashPlan DB.  The number of files to update can decrease by 10 or more at time.

While this "file check" is happening, I've looked at my Synology resource monitor and it seems that nothing if being uploaded. 

I tried deleting the container and clearing the cache.  That didn't help.

Any thoughts?  Is this a separate issue?

thanks 

Hal
![afterScan](https://user-images.githubusercontent.com/17240107/146987978-315658a9-6430-4c71-b9ad-e45b494fd0a4.jpg)

**Comment by halteach** [comment]
Is there anyway to see what files are in the list of files to be uploaded?

**Comment by madfusker** [comment]
Yes, look at your logs.  

For the most part nothing is being uploaded, but for some reason it feels it needs to verify all those files over and over again so it shows it flying through all those GB of files very quickly.  If any files do change, at least in my case, they are being uploaded.

**Comment by halteach** [comment]
> Yes, look at your logs.
> 
> For the most part nothing is being uploaded, but for some reason it feels it needs to verify all those files over and over again so it shows it flying through all those GB of files very quickly. If any files do change, at least in my case, they are being uploaded.

Where are the logs?

and thanks!

hal

**Comment by madfusker** [comment]
Depends where you have it.  :)
/share/Docker/appdata/crashplan-pro/log for me...

**Comment by axemanozh** [comment]
I finally got around to opening a ticket with Code42 today. I don't expect any immediate response or resolution from them, given the Holiday, but I may ask for some help on here depending on what they ask for in regards to disguising the fact my CrashPlan instance is running in a Docker environment on a NAS. I will otherwise update this thread if they are able to resolve the issue.

**Comment by jlesage** [comment]
Great, thanks!

**Comment by theRealKLH** [comment]
I don't know if it is the same situation that I was experiencing, but... This was happening to me for about two months straight. every day it would do a sync procedure then began backup.. THEN right back to sync. The sync process took so long (4-6 days) that backups wouldn't actually run. I finally put a ticket in and they had to FORCE the syncronization to complete. It had something to do with the 60 day maintenance or some such. I guess getting ready for the "we are going to delete all your over 90 day deleted files" .

**Comment by madfusker** [comment]
Crazy...   My archive is about 2.5TB and the rinse and repeat process has been:

1) Sync block info for 8-10 hours, sometimes to 145% which is weird
2) Fast verify about 500GB of files which look like it's backing up at supersonic speed, but it's really just verifying
3) Show everything all 100% backed up for <30 minutes, then
4) Start over on step 1 with block sync....

I believe it did this for weeks.  Then a couple days ago it started a prune deep and started actually backing up about 200G of photos I put on the NAS in early November (not the fast verify, real backup because my connection is pegged).  It's been working on them a couple days now!  So,,, it looks like it never backed them up which is super frustrating, and this 20-25 repeated block syncs must have found them.  I haven't changed a single line in my docker compose command, so something in that update a few days ago made them discoverable.  Or, they did something on backend which is more likely.  I don't get it.  But I am kinda glad Crashplan is my secondary backup behind Borg.  Still, a secondary backup should just work!  My god! Crashplan needs to get their S together!  That on top of deleting all my deleted files older than 90 days has me a bit bent at the moment!

**Comment by halteach** [comment]
I have the issue number 2 above (different number of files):

> "2: Fast verify about 500GB of files which look like it's backing up at supersonic speed, but it's really just verifying"

The number of files is always within a 10 of 24370 and it takes about 30 minutes to go through them and decided nothing has to be updated. 

I have tried tried 

1. deleting the container
2. erasing the cache 
3. forcing a maintenance with deep prune
4. I have looked in the log files and can't find anything I can understand (like a list of the 24000+ files)

any suggestions?

**Comment by halteach** [comment]
let me add that this is what appears in the backup_files.log.0 file"

I 12/27/21 12:31PM 42 [Synology021118 Backup Set] Starting backup to CrashPlan Central: 24,370 files (66.70GB) to back up
I 12/27/21 01:04PM 42 [Synology021118 Backup Set] Completed backup to CrashPlan Central: No new data to backup at this time


hal

**Comment by madfusker** [comment]
Update from my side:  So after backing up everything it missed over the last 60 days, it hasn't done the repeated block sync for 3 days now.  I think it has settled.  BUT, it did go through and prune everything older than 90 days.  A month or so ago I noticed they changed my retention setting from NEVER, to delete deleted files after 90 days.  I changed it back as I need a minimum of 12 months on some backup sets, but now I see the only option is 90 days.  What a bunch of BS!  They changed this without me know and they continue to find ways to delete our data to save on their bottom line.  Totally unacceptable!  I guess I will have to move to Backblaze BZ2 for my secondary backups now and just rclone it.  I've been a crashplan customer since 2013, and it's been downhill ever since....

Thanks for the tremendous work over the years jlesage!  I've been happy to support you for your work here with several donations over they years and I hope others are as well.  It's no small task to maintain this and in my book you've been a hero to the community.  Crashplan is still a pretty great service, it just no longer fits what I need.

**Comment by axemanozh** [comment]
> Update from my side: So after backing up everything it missed over the last 60 days, it hasn't done the repeated block sync for 3 days now. I think it has settled. BUT, it did go through and prune everything older than 90 days. A month or so ago I noticed they changed my retention setting from NEVER, to delete deleted files after 90 days. I changed it back as I need a minimum of 12 months on some backup sets, but now I see the only option is 90 days. What a bunch of BS! They changed this without me know and they continue to find ways to delete our data to save on their bottom line. Totally unacceptable! I guess I will have to move to Backblaze BZ2 for my secondary backups now and just rclone it. I've been a crashplan customer since 2013, and it's been downhill ever since....
> 
> Thanks for the tremendous work over the years jlesage! I've been happy to support you for your work here with several donations over they years and I hope others are as well. It's no small task to maintain this and in my book you've been a hero to the community. Crashplan is still a pretty great service, it just no longer fits what I need.

FWIW, I personally think Backblaze is a superior product to CrashPlan; I used it for a few years but migrated back to Crashplan since I couldn't justify the cost of B2 for a personal home backup compared to CrashPlan's $10/month. There are some people who set their NAS to an iSCSI LUN and are able to use Backblaze's personal backup with a separate PC as an iSCSI initiator (Intel NUC or similar with a low power draw) so it is seen as a local drive on that machine, and the cost is $7/month for unlimited storage. I've thought about doing this, but it just isn't worth the hassle right now of having to offload the data from my NAS, reconfigure my storage pool, and then reupload all of my data to a new service. YMMV.

And, yes, thanks to @jlesage for all of his great work on this container. I make it a point to donate once a year as a way to support his work.

**Comment by axemanozh** [comment]
I also finally heard from CrashPlan support today; they mentioned something about a conflict between maintenance and the scheduled verification scans, and had me change the verification scan schedule from daily to every 3 days, as well as increase the amount of memory I had allocated to the container. We'll monitor and see how it goes.

**Comment by halteach** [comment]
how much memory?

**Comment by axemanozh** [comment]
> how much memory?

I had it set to 4 GB, admittedly less than the 1 GB per TB of data recommended by Crashplan. I've never had any problems before, but they said they saw Crashplan exceeding my memory allocation (not sure where that is visible, as I never saw anything about it in the logs). They asked me to increase it to around 5 GB, but I just maxed it out to the 8 GB of total RAM that is currently installed on my NAS, I'll get around to buying some new DIMMs at some point to give myself even more wiggle room.

**Comment by axemanozh** [comment]
As an update on my support request with CrashPlan, the initial steps they wanted me to try have had no affect. They have now had me deauthorize the machine, and will tell me when to sign back in after maintenance has completed - as mentioned earlier in this thread by @jlesage.

**Comment by halteach** [comment]
> As an update on my support request with CrashPlan, the initial steps they wanted me to try have had no affect. They have now had me deauthorize the machine, and will tell me when to sign back in after maintenance has completed - as mentioned earlier in this thread by @jlesage.

what does "deauthorize" mean?

**Comment by jlesage** [comment]
> what does "deauthorize" mean?

This operation is used to disconnect/logout the CrashPlan instance from the cloud.  This is to make sure that CrashPlan doesn't backup anything during the maintenance period.

**Comment by halteach** [comment]
> This operation is used to disconnect/logout the CrashPlan instance from the cloud. This is to make sure that CrashPlan doesn't backup anything during the maintenance period.

how  do you do that?  It seems you have to sign out.  I'm don't know how to do that.

sorry for the dumb question.

**Comment by halteach** [comment]
okay, I think I found it:


![image](https://user-images.githubusercontent.com/17240107/147851151-5ae54582-6d31-439e-8502-bb693998d560.png)

**Comment by jlesage** [comment]
This is normally done by using the CrashPlan cli (Shift+Ctrl+C).  But you can also just stop the container.

**Comment by axemanozh** [comment]
> This is normally done by using the CrashPlan cli (Shift+Ctrl+C). But you can also just stop the container.

This is what CrashPlan support had me do.

**Comment by theRealKLH** [comment]
> > This is normally done by using the CrashPlan cli (Shift+Ctrl+C). But you can also just stop the container.
> 
> This is what CrashPlan support had me do.

They had me doubleclick the CODE42 logo (in the container) and type in deauthorize...

**Comment by axemanozh** [comment]
Another update to my support request with CrashPlan: Unfortunately the issue is still occurring after leaving my container unauthorized while maintenance completed. Every time a verification scan takes place, it identifies nearly the entire backup selection as needing to re-upload to CrashPlan Online (which then fast verifies but still takes over 12 hours due to the size of my backup.) Awaiting to see what else CrashPlan can do.

**Comment by halteach** [comment]
I have a similar issue, 2400o files on the "todo list" every scan (as stated earlier).  I've been going back and forth with support over this.  I haven't gotten a cogent response yet.

**Comment by zsostaric** [comment]
Same here. The temporary fix is to change the verification scan not to occur every night, but for example every 7 days so then you have a "working" crashplan for 6 days until the next verification occurs :)

**Comment by theRealKLH** [comment]
This reverification is also happening to me since beginning of December. Haven't "succesfully" completed a backup for a LONG time.

**Comment by axemanozh** [comment]
Unfortunately my support case with CrashPlan is going nowhere but there are enough other people on this thread also experiencing the issue that I’m confident the issue is something on CrashPlan’s backend. Hopefully their engineers are looking into it.

**Comment by halteach** [comment]
So I finally heard back from Crashplan.  They figured out I was using it on a Synology NAS (I never told them) and they said because it was an unsupported device I was on my own.

**Comment by axemanozh** [comment]
> So I finally heard back from Crashplan. They figured out I was using it on a Synology NAS (I never told them) and they said because it was an unsupported device I was on my own.

Bummer, I wonder how they figured that out. I know @jlesage has mentioned in the past that he takes steps to disguise the fact his container is running in a docker environment from CrashPlan. It might be because I see you named your backup set "Synology" in a screenshot from a previous post.

**Comment by halteach** [comment]
Yes that was probably it. So no great sleuthing on crapshoot crashplan's
part.

**Comment by halteach** [comment]
So after the update to 8.8.2 I'm still seeing the same behavior.  It identifies 24000+ files to be backed up. it takes about 20 -25 minutes to run and only a few new files are backed up. 

Is there a log that lists what files are on the "todo list"?

**Comment by jlesage** [comment]
Did you try to look at `log/service.log.0` ?  Maybe the problem is that these files cannot be read by CrashPlan ?

**Comment by halteach** [comment]
> Did you try to look at `log/service.log.0` ? Maybe the problem is that these files cannot be read by CrashPlan ?

Not sure what to look for and not sure what you mean by "cannot be read by Crashplan"  BTW, I did look at and I didn't see any blatant errors or exceptions.

**Comment by ThorEgilGit** [comment]
Same problem here. A continuous loop of block sync/file sync/back up (verifying up to 7 TB every time) going on for at least the last month. And some deep pruning now and then.
It does seem to back up my new files though.

**Comment by axemanozh** [comment]
Welp, CrashPlan support is now telling me the whole block sync and appearing to re-upload the entire selection is expected behavior. I have asked them to clarify as I never saw it behave this way before the December 2021 timeframe, and judging from the other replies in this thread, I'm guessing most others didn't either.

**Comment by halteach** [comment]
Well, before they told me that they don't support synology, I got a similar repsonse that this was typical behavior even though my december logs "say" otherwise.

> Welp, CrashPlan support is now telling me the whole block sync and appearing to re-upload the entire selection is expected behavior. I have asked them to clarify as I never saw it behave this way before the December 2021 timeframe, and judging from the other replies in this thread, I'm guessing most others didn't either.

**Comment by axemanozh** [comment]
I've finally gotten to a point where CrashPlan support is asking to pull logs from my device. 

@jlesage Any advice on how to go about this, i.e. disguising that my agent is running in a Docker environment on a NAS?

**Comment by jlesage** [comment]
To my knowledge, there is no indication from the logs that CrashPlan is running in a container.

Just make sure the name of your device and/or the name of your backup set don't provide hints about your actual NAS (for example the names should not contain Synology or QNAP).

If you don't want to send too much logs, you can stop the container, rename the `log` folder inside the directory you mapped to `/config` (e.g. to `log.old`) and then finally start the container again.  This way, you will sent only recent logs.

**Comment by axemanozh** [comment]
@jlesage So this is the response I got from CrashPlan support after they reviewed my logs:

**Thank you for your patience while we investigate this issue. Looking through your logs, it appears you are using a kind of media server or media management tool that sorts and updates files and their metadata - /storage1/. Because of this, it is showing up to CrashPlan as new block changes to those files.

Can you confirm that this is the case? What is /storage1/ and how is it attached?**

Storage1 is of course my QNAP storage volume. Any good ideas on how I can respond to this without giving up that I'm running CrashPlan on a NAS?

**Comment by axemanozh** [comment]
> @jlesage So this is the response I got from CrashPlan support after they reviewed my logs:
> 
> **Thank you for your patience while we investigate this issue. Looking through your logs, it appears you are using a kind of media server or media management tool that sorts and updates files and their metadata - /storage1/. Because of this, it is showing up to CrashPlan as new block changes to those files.
> 
> Can you confirm that this is the case? What is /storage1/ and how is it attached?**
> 
> Storage1 is of course my QNAP storage volume. Any good ideas on how I can respond to this without giving up that I'm running CrashPlan on a NAS?

Investigating a little more in my QNAP environment after CrashPlan's response, I found that Multimedia Services were still enabled (I thought I had disabled them), even after removing the Multimedia Console application from QNAP. It seems this might have been indexing files in the background all this time, which may have been causing the block sync behavior as noted by QNAP. I don't know why that would have picked up out of the blue in the November/December timeframe but I'll monitor and see if this resolves it. If so, goodness gracious, what a dumb root cause for me pounding my head on the table for 3 months trying to figure it out.

**Comment by jlesage** [comment]
So the issue is that the QNAP Media Service change the files all the time ?  What the service is doing exactly to the files ?

**Comment by axemanozh** [comment]
> So the issue is that the QNAP Media Service change the files all the time ? What the service is doing exactly to the files ?

I don't know that definitively yet; I'll have to monitor and confirm. The service scrapes files for indexing and to generate thumbnails. I didn't see timestamps on files being changed or anything like that so I'm not sure what it might be changing at the block level that CrashPlan is pickup on but the vast majority of my storage volume is composed of multimedia files so it would make sense.

I thought I had the service disabled but checking under Control Panel -> System Status -> System Service on the QNAP device, it showed the Multimedia Services still running in the background. I had to download the Multimedia Console QPKG app from the QNAP App Center and toggle it off to remove it.

If this has worked (I won't know for a day or two), I'll come back and update the thread. If not, I'll have to make some type of response to CrashPlan support - I'm still not sure what I'd tell them in that instance.

**Comment by theRealKLH** [comment]
naw dude. I call BS.. I am not running indexing on my files everyday. CP changed (or broke) something and they aren't fessing up. Too many people with this same kind of issue. Check out my log.. starts backup and erroroneous claims 17.5tb to backup (17.5tb is total already on CP.. yeah it's "big"[NOT] so sue me!). it stops the backup does a FULL system scan then starts the backup with a realistic 37.3GB to backup. STOPS the backup for yet ANOTHER full system scan, then starts the backup again.. once again claiming it needs to backup 17.5TB. THEN it stops the backup again to do a complete "syncronizing block information" for the next 22 or so hours. 
![image](https://user-images.githubusercontent.com/65736720/157808017-53f8cb55-ad86-4f05-9cca-0640eea3af1e.png)

heh.. and my status right now...
![image](https://user-images.githubusercontent.com/65736720/157808283-9c667f6f-b74e-447e-af6f-ddef4ebb70f4.png)

It's comical because I was JUST fine before they announced that "no deleted files over 90 days" policy for the end of last year.

**Comment by axemanozh** [comment]
> naw dude/dudette. I call BS.. I am not running indexing on my files everyday. CP changed (or broke) something and they aren't fessing up. Too many people with this same kind of issue. Check out my log.. starts backup and erroroneous claims 17.5tb to backup (17.5tb is total already on CP.. yeah it's "big"[NOT] so sue me!). it stops the backup does a FULL system scan then starts the backup with a realistic 37.3GB to backup. STOPS the backup for yet ANOTHER full system scan, then starts the backup again.. once again claiming it needs to backup 17.5TB. THEN it stops the backup again to do a complete "syncronizing block information" for the next 22 or so hours. ![image](https://user-images.githubusercontent.com/65736720/157808017-53f8cb55-ad86-4f05-9cca-0640eea3af1e.png)
> 
> heh.. and my status right now... ![image](https://user-images.githubusercontent.com/65736720/157808283-9c667f6f-b74e-447e-af6f-ddef4ebb70f4.png) It's comical because I was JUST fine before they announced that "no deleted files over 90 days" policy for the end of last year.

Like I said, I don't know definitively this is the problem; it's just the closest I've come to explanation thus far. I agree I am skeptical since there are other people out there having the same issue, and I never had the problem prior to the December CrashPlan release. But it's worth a try to see if it works.

**Comment by axemanozh** [comment]
> > naw dude/dudette. I call BS.. I am not running indexing on my files everyday. CP changed (or broke) something and they aren't fessing up. Too many people with this same kind of issue. Check out my log.. starts backup and erroroneous claims 17.5tb to backup (17.5tb is total already on CP.. yeah it's "big"[NOT] so sue me!). it stops the backup does a FULL system scan then starts the backup with a realistic 37.3GB to backup. STOPS the backup for yet ANOTHER full system scan, then starts the backup again.. once again claiming it needs to backup 17.5TB. THEN it stops the backup again to do a complete "syncronizing block information" for the next 22 or so hours. ![image](https://user-images.githubusercontent.com/65736720/157808017-53f8cb55-ad86-4f05-9cca-0640eea3af1e.png)
> > heh.. and my status right now... ![image](https://user-images.githubusercontent.com/65736720/157808283-9c667f6f-b74e-447e-af6f-ddef4ebb70f4.png) It's comical because I was JUST fine before they announced that "no deleted files over 90 days" policy for the end of last year.
> 
> Like I said, I don't know definitively this is the problem; it's just the closest I've come to an explanation thus far. I agree I am skeptical since there are other people out there having the same issue, and I never had the issue prior to the December CrashPlan release. But it's worth a try to see if it works.

And no go on that. Same behavior. Now I have to explain to CrashPlan support what my storage1 variable is - any ideas on that? I'm thinking I'm just going to say it's how I have my drives mapped in my Linux install?

**Comment by jlesage** [comment]
I guess you can tell that you had a media software that was indexing files and that you removed that software.  Else, you might ask to clarify their previous answer.

**Comment by jlesage** [comment]
You can check on your side in `service.log.0` to see what the log is saying about files under `/storage1`.  Also, for these files, do you see their size, date, etc changing over time ?

**Comment by axemanozh** [comment]
> You can check on your side in `service.log.0` to see what the log is saying about files under `/storage1`. Also, for these files, do you see their size, date, etc changing over time ?

Thanks, I took a look through the log and don't see anything that looks particularly noteworthy. I'm not as familiar with Linux as I am Windows UNC but the storage1 variable just looks more or less like a drive path. I'll just tell them that's how I have my directories mapped. I never did see metadata changing (looking only at timestamps on the NAS shares mapped to my Windows machine) so I'm not positive anything definitely was happening; I just noticed that the QNAP Multimedia service was still enabled and logically it seemed like it might be causing changes that CrashPlan was picking up on.

**Comment by axemanozh** [comment]
Just as a (presumably) final update on this, they are pointing at other applications running in my environment as updating metadata or whatnot on my files which is causing the resync behavior (even though this never happened before the November-December timeframe), and have all but said there is nothing more they can do. I've more or less learned to live with it at this point, so I guess it is what it is and maybe someday some CrashPlan update might somehow fix the issue.

**Comment by digiblur** [comment]
Looks like I got hit with this recently on a 6TB backup set.  Constant loop of synchronizing block info, seems like it just starts over.  Not sure if it reaches 100% ever.  Any quick fix tricks or alternative options out there I should look up?  I've been thinking of changing given I have gig upload now and Crashplan doesn't touch anyways with their slow uptake rate.

**Comment by axemanozh** [comment]
> Looks like I got hit with this recently on a 6TB backup set. Constant loop of synchronizing block info, seems like it just starts over. Not sure if it reaches 100% ever. Any quick fix tricks or alternative options out there I should look up? I've been thinking of changing given I have gig upload now and Crashplan doesn't touch anyways with their slow uptake rate.

I hate to move away from Jocelyn’s solution, because it does work and is so well-maintained, but I’ve been experimenting with the Backblaze Personal Docker by tessypowder, and it works well after you figure out the initial setup. As a bonus, I personally think Backblaze is a superior product to CrashPlan and the cost per month is less, to boot. The option to have any potential restores sent to you by a USB drive rather than Internet download is also particularly appealing.

https://hub.docker.com/r/tessypowder/backblaze-personal-wine

**Comment by digiblur** [comment]
@axemanozh I have heard the restore is a joke for them unless you use the usb method. I might as well give them a shot since this one is stuck.

**Comment by jlesage** [comment]
@digiblur, according to the information we have so far about this issue, it might be caused be maintenance done on CrashPlan servers.  Problem could be temporary and you might want to stop the container for a few days to allow the maintenance to terminate.

**Comment by digiblur** [comment]
I did stop it for 12 hours and see, it looks like it picks up at the exact point it was at.  I'll leave it stopped for the weekend and see how it goes.  

Thanks for the info and response!
