### ISSUE TITLE
Can't Connect To Server After Container Deployment

### ISSUE THREAD

**Issue by LeeTaylorX12** [jlesage/docker-crashplan-pro#449]
### Current Behavior

Can't get past the initial login screen in order to reclaim/restart backup process - Error message displayed "Unable to Sign In.  Can't Connect to Server".  Have been running / re-creating for years with no issues.

Connectivity seems to be working fine within the contrainer .. can ping crashplan.com 

### Expected Behavior

To be able to login

### Environment

Proxmox / LXC / Ubuntu / CephFuse

Tried upgrade on packages and moving to latest ubuntu version (23.10)

### Container creation

I use portainer to manage my dockers - this is the stack used to create

`version: '3'

services:
  crashplan-pro:
    image:  jlesage/crashplan-pro
    container_name: crashplanPro4
    environment:
      - TZ=Europe/London
      - PUID=1000
      - PGID=1000
      - CRASHPLAN_SRV_MAX_MEM=9162m
      #- APP_NICENESS=-20
    volumes:
      - crashplanConfig4:/config
      # - media:/PlexMedia 
      - /mnt/media:/PlexMedia
      - /mnt/backup:/backup
    ports:
      - 5800:5800 
      - 5900:5900 
    restart: unless-stopped

volumes:
  crashplanConfig4:`

### Container log

```text
[12.15.23 11:07:12.656 INFO  main           com.backup42.service.CPService]   READY!    Unauthorized    Listening HTTPS port 4243. Startup in 3.012 s
[12.15.23 11:07:12.657 INFO  main           com.backup42.service.CPService] *****************************************************************************************
[12.15.23 11:07:12.658 INFO  -11-thread-1 2.manifest.InstallationValidator] Completed file validation: Success{payload=null}
[12.15.23 11:07:12.658 INFO  -11-thread-1 2.manifest.InstallationValidator] Installation validation result: Success{payload=null}
[12.15.23 11:07:12.659 INFO  -11-thread-1 ction.TamperDetectionServiceImpl] TAMPER:: Finished after 2.029 s with result: Success{payload=null}
[12.15.23 11:07:12.659 INFO  EventBus 0   ction.TamperDetectionServiceImpl] TAMPER:: Initiating Tamper Detection using CRL(true) and cpg-agent-code-signatures-11.2.0.520.jar...
[12.15.23 11:07:12.659 INFO  EventBus 0   ction.TamperDetectionServiceImpl] TAMPER:: Using search path: /usr/local/crashplan/lib
[12.15.23 11:07:12.659 INFO  EventBus 0   2.manifest.InstallationValidator] Begin validating software installation
[12.15.23 11:07:12.669 INFO  EventBus 0   42.manifest.ManifestJarValidator] Retrieved certificate chain: length=3
[12.15.23 11:07:12.669 INFO  EventBus 0   42.manifest.ManifestJarValidator] Validated certificate as signed by Crashplan Software
[12.15.23 11:07:12.765 INFO  EventBus 0   42.manifest.ManifestJarValidator] Validated certificate path
[12.15.23 11:07:12.765 WARN  EventBus 0   42.manifest.ManifestJarValidator] Unable to validate certificate revocation status., [java.security.cert.CertPathValidatorException: Could not determine revocation status]
[12.15.23 11:07:12.765 INFO  EventBus 0   42.manifest.ManifestJarValidator] Validated certificate chain
[12.15.23 11:07:12.766 INFO  EventBus 0   2.manifest.InstallationValidator] Validated Manifest JAR
[12.15.23 11:07:13.436 INFO  EventBus 0   2.manifest.InstallationValidator] Completed file validation: Success{payload=null}
[12.15.23 11:07:13.436 INFO  EventBus 0   2.manifest.InstallationValidator] Installation validation result: Success{payload=null}
[12.15.23 11:07:13.437 INFO  EventBus 0   ction.TamperDetectionServiceImpl] TAMPER:: Finished after 777.5 ms with result: Success{payload=null}
[12.15.23 11:07:13.437 INFO  EventBus 0   ice.deployment.DeploymentService] Deploy:: No deployment URL available, not attempting deployment package processing
[12.15.23 11:07:16.738 INFO  055254758-59 zation.CustomizationApiClientCmd] ClientCustomization:: Getting preAuthenticated customizations
[12.15.23 11:07:16.739 INFO  055254758-59 on.CustomizationUniversalService] ClientCustomization:: Unable to get preLogin client customization data from the server, for deploymentPolicyToken. serverUrl = Optional.empty Error message= Unable to build PreLoginClientCustomization request. The server url is not set.
[12.15.23 11:07:42.569 INFO  eduledSrvc-0 e42.service.uiinfo.UIInfoUtility] Loaded address=127.0.0.1, port=4243, token, and validateCertificate=true from location=/var/lib/crashplan/.ui_info
[12.15.23 11:07:59.305 INFO  re-event-2-3 abre.SabrePendingChannelListener] SABRE::Channel connect failed for guid 4200, cause=java.net.UnknownHostException: SMB
[12.15.23 11:07:59.305 INFO  re-event-2-3 .handler.ChannelLifecycleHandler] SABRE:: Channel became inactive. closedBy=THIS_SIDE, channel=[id: 0x9e91c717], sessionState=RemotePeer-[guid=4200, state=CONNECTING]; Session-[localID=1144023056830437771, remoteID=0, closed=false, expiration=null, remoteIdentity=ENDPOINT, local=null, remote=null]
[12.15.23 11:07:59.306 INFO  re-event-2-3                      SabreLogger] Channel failed to reach state for app protocol start. reason=javax.net.ssl.SSLHandshakeException: SslHandler removed before handshake completed, channel=[id: 0x9e91c717]
[12.15.23 11:07:59.309 INFO  er1WeDftWkr0 up42.service.peer.PeerController] DENIED! Ignore connect, we are not authorized.
[12.15.23 11:07:59.309 INFO  er1WeDftWkr0 ging.direct.DirectNetworkChannel] Channel became inactive. closedBy=THIS_SIDE, reason='Session close', channel=DIRECT
[12.15.23 11:08:11.754 INFO  ystemWatcher p42.service.peer.CPCConnectCheck] Connect to CPC after 0ms
[12.15.23 11:08:11.754 INFO  ystemWatcher up42.service.peer.PeerController] Attempting to connect to CPC. delay=30000
[12.15.23 11:08:11.757 INFO  re-event-2-4 abre.SabrePendingChannelListener] SABRE::Channel connect failed for guid 4200, cause=java.net.UnknownHostException: SMB
[12.15.23 11:08:11.757 INFO  re-event-2-4 .handler.ChannelLifecycleHandler] SABRE:: Channel became inactive. closedBy=THIS_SIDE, channel=[id: 0xde5f00af], sessionState=RemotePeer-[guid=4200, state=CONNECTING]; Session-[localID=1144023077701294475, remoteID=0, closed=false, expiration=null, remoteIdentity=ENDPOINT, local=null, remote=null]
[12.15.23 11:08:11.757 INFO  re-event-2-4                      SabreLogger] Channel failed to reach state for app protocol start. reason=javax.net.ssl.SSLHandshakeException: SslHandler removed before handshake completed, channel=[id: 0xde5f00af]
[12.15.23 11:08:15.253 INFO  055254758-65 up42.service.peer.PeerController] Attempting to connect to CPC. delay=30000
[12.15.23 11:08:15.256 INFO  re-event-2-1 abre.SabrePendingChannelListener] SABRE::Channel connect failed for guid 4200, cause=java.net.UnknownHostException: SMB
[12.15.23 11:08:15.256 INFO  re-event-2-1 .handler.ChannelLifecycleHandler] SABRE:: Channel became inactive. closedBy=THIS_SIDE, channel=[id: 0x0922f828], sessionState=RemotePeer-[guid=4200, state=CONNECTING]; Session-[localID=1144023083573320075, remoteID=0, closed=false, expiration=null, remoteIdentity=ENDPOINT, local=null, remote=null]
[12.15.23 11:08:15.256 INFO  re-event-2-1                      SabreLogger] Channel failed to reach state for app protocol start. reason=javax.net.ssl.SSLHandshakeException: SslHandler removed before handshake completed, channel=[id: 0x0922f828]
[12.15.23 11:08:22.769 INFO  re-event-2-2 abre.SabrePendingChannelListener] SABRE::Channel connect failed for guid 4200, cause=java.net.UnknownHostException: SMB
[12.15.23 11:08:22.770 INFO  re-event-2-2 .handler.ChannelLifecycleHandler] SABRE:: Channel became inactive. closedBy=THIS_SIDE, channel=[id: 0x9e6079ce], sessionState=RemotePeer-[guid=4200, state=CONNECTING]; Session-[localID=1144023096189786507, remoteID=0, closed=false, expiration=null, remoteIdentity=ENDPOINT, local=null, remote=null]
[12.15.23 11:08:22.770 INFO  re-event-2-2                      SabreLogger] Channel failed to reach state for app protocol start. reason=javax.net.ssl.SSLHandshakeException: SslHandler removed before handshake completed, channel=[id: 0x9e6079ce]
[12.15.23 11:08:26.266 INFO  re-event-2-3 abre.SabrePendingChannelListener] SABRE::Channel connect failed for guid 4200, cause=java.net.UnknownHostException: SMB
[12.15.23 11:08:26.267 INFO  re-event-2-3 .handler.ChannelLifecycleHandler] SABRE:: Channel became inactive. closedBy=THIS_SIDE, channel=[id: 0x3b6c5d7a], sessionState=RemotePeer-[guid=4200, state=CONNECTING]; Session-[localID=1144023102045034891, remoteID=0, closed=false, expiration=null, remoteIdentity=ENDPOINT, local=null, remote=null]
[12.15.23 11:08:26.267 INFO  re-event-2-3                      SabreLogger] Channel failed to reach state for app protocol start. reason=javax.net.ssl.SSLHandshakeException: SslHandler removed before handshake completed, channel=[id: 0x3b6c5d7a]
[12.15.23 11:08:33.781 INFO  re-event-2-4 abre.SabrePendingChannelListener] SABRE::Channel connect failed for guid 4200, cause=java.net.UnknownHostException: SMB
[12.15.23 11:08:33.781 INFO  re-event-2-4 .handler.ChannelLifecycleHandler] SABRE:: Channel became inactive. closedBy=THIS_SIDE, channel=[id: 0x56c1ca18], sessionState=RemotePeer-[guid=4200, state=CONNECTING]; Session-[localID=1144023114678278539, remoteID=0, closed=false, expiration=null, remoteIdentity=ENDPOINT, local=null, remote=null]
[12.15.23 11:08:33.782 INFO  er1WeDftWkr1 up42.service.peer.PeerController] DENIED! Ignore connect, we are not authorized.
[12.15.23 11:08:33.782 INFO  re-event-2-4                      SabreLogger] Channel failed to reach state for app protocol start. reason=javax.net.ssl.SSLHandshakeException: SslHandler removed before handshake completed, channel=[id: 0x56c1ca18]
[12.15.23 11:08:33.782 INFO  er1WeDftWkr1 ging.direct.DirectNetworkChannel] Channel became inactive. closedBy=THIS_SIDE, reason='Session close', channel=DIRECT
[12.15.23 11:08:37.278 INFO  re-event-2-1 abre.SabrePendingChannelListener] SABRE::Channel connect failed for guid 4200, cause=java.net.UnknownHostException: SMB
[12.15.23 11:08:37.278 INFO  re-event-2-1 .handler.ChannelLifecycleHandler] SABRE:: Channel became inactive. closedBy=THIS_SIDE, channel=[id: 0x353bd61e], sessionState=RemotePeer-[guid=4200, state=CONNECTING]; Session-[localID=1144023120516749707, remoteID=0, closed=false, expiration=null, remoteIdentity=ENDPOINT, local=null, remote=null]
[12.15.23 11:08:37.278 INFO  re-event-2-1                      SabreLogger] Channel failed to reach state for app protocol start. reason=javax.net.ssl.SSLHandshakeException: SslHandler removed before handshake completed, channel=[id: 0x353bd61e]
[12.15.23 11:08:41.789 INFO  ystemWatcher up42.service.peer.PeerController]   Couldn't connect to CPC at known location, attempting to connect to CPC via authority fallbacks list
[12.15.23 11:08:41.789 WARN  ystemWatcher up42.service.peer.PeerController]   Couldn't connect to CPC using authority fallbacks, nothing else to do.
[12.15.23 11:08:45.285 INFO  055254758-65 up42.service.peer.PeerController]   Couldn't connect to CPC at known location, attempting to connect to CPC via authority fallbacks list
[12.15.23 11:08:45.287 WARN  055254758-65 up42.service.peer.PeerController]   Couldn't connect to CPC using authority fallbacks, nothing else to do.
[12.15.23 11:08:45.287 WARN  055254758-65 42.service.peer.DefaultMessenger] Unable to send message com.code42.protos.shared.login.LoginConfigurationMessages$LoginConfigurationRequest, unknown peer 4200
[12.15.23 11:09:07.279 INFO  er1WeDftWkr0 up42.service.peer.PeerController] DENIED! Ignore connect, we are not authorized.
[12.15.23 11:09:07.279 INFO  er1WeDftWkr0 ging.direct.DirectNetworkChannel] Channel became inactive. closedBy=THIS_SIDE, reason='Session close', channel=DIRECT
[12.15.23 11:09:22.281 INFO  re-event-2-2 abre.SabrePendingChannelListener] SABRE::Channel connect failed for guid 4200, cause=java.net.UnknownHostException: SMB
[12.15.23 11:09:22.281 INFO  re-event-2-2 .handler.ChannelLifecycleHandler] SABRE:: Channel became inactive. closedBy=THIS_SIDE, channel=[id: 0x965e5def], sessionState=RemotePeer-[guid=4200, state=CONNECTING]; Session-[localID=1144023196030998923, remoteID=0, closed=false, expiration=null, remoteIdentity=ENDPOINT, local=null, remote=null]
[12.15.23 11:09:22.281 INFO  re-event-2-2                      SabreLogger] Channel failed to reach state for app protocol start. reason=javax.net.ssl.SSLHandshakeException: SslHandler removed before handshake completed, channel=[id: 0x965e5def]
[12.15.23 11:09:52.282 INFO  er1WeDftWkr0 up42.service.peer.PeerController] DENIED! Ignore connect, we are not authorized.
[12.15.23 11:09:52.282 INFO  er1WeDftWkr0 ging.direct.DirectNetworkChannel] Channel became inactive. closedBy=THIS_SIDE, reason='Session close', channel=DIRECT
[12.15.23 11:10:37.284 INFO  re-event-2-3 abre.SabrePendingChannelListener] SABRE::Channel connect failed for guid 4200, cause=java.net.UnknownHostException: SMB
[12.15.23 11:10:37.284 INFO  re-event-2-3 .handler.ChannelLifecycleHandler] SABRE:: Channel became inactive. closedBy=THIS_SIDE, channel=[id: 0xae412b8e], sessionState=RemotePeer-[guid=4200, state=CONNECTING]; Session-[localID=1144023321876896139, remoteID=0, closed=false, expiration=null, remoteIdentity=ENDPOINT, local=null, remote=null]
[12.15.23 11:10:37.284 INFO  re-event-2-3                      SabreLogger] Channel failed to reach state for app protocol start. reason=javax.net.ssl.SSLHandshakeException: SslHandler removed before handshake completed, channel=[id: 0xae412b8e]
[12.15.23 11:10:37.285 INFO  er1WeDftWkr0 up42.service.peer.PeerController] DENIED! Ignore connect, we are not authorized.
[12.15.23 11:10:37.285 INFO  er1WeDftWkr0 ging.direct.DirectNetworkChannel] Channel became inactive. closedBy=THIS_SIDE, reason='Session close', channel=DIRECT
```

**Comment by jlesage** [comment]
Could you share the output of `docker logs <container name>` and `docker inspect <container name>` ?

**Comment by LeeTaylorX12** [comment]
docker log
[cont-init   ] 89-info.sh: executing...
    ╭――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――╮
    │                                                                      │
    │ Application:           CrashPlan                                     │
    │ Application Version:   11.2.0                                        │
    │ Docker Image Version:  23.11.4                                       │
    │ Docker Image Platform: linux/amd64                                   │
    │                                                                      │
    ╰――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――╯
[cont-init   ] 89-info.sh: terminated successfully.
[cont-init   ] all container initialization scripts executed.
[init        ] giving control to process supervisor.
[supervisor  ] loading services...
[supervisor  ] loading service 'default'...
[supervisor  ] loading service 'logrotate'...
[supervisor  ] loading service 'logmonitor'...
[supervisor  ] loading service 'app'...
[supervisor  ] loading service 'CrashPlanEngine'...
[supervisor  ] loading service 'gui'...
[supervisor  ] loading service 'openbox'...
[supervisor  ] loading service 'xvnc'...
[supervisor  ] loading service 'certsmonitor'...
[supervisor  ] service 'certsmonitor' is disabled.
[supervisor  ] loading service 'nginx'...
[supervisor  ] all services loaded.
[supervisor     ] starting services...
[supervisor     ] starting service 'logmonitor'...
[logmonitor     ] Monitoring log file: /config/log/service.log.0
[logmonitor     ] Monitoring status file: /config/log/app.log
[supervisor     ] starting service 'CrashPlanEngine'...
[supervisor     ] starting service 'xvnc'...
[xvnc           ] Xvnc TigerVNC 1.13.1 - built Nov 17 2023 22:53:44
[xvnc           ] Copyright (C) 1999-2022 TigerVNC Team and many others (see README.rst)
[xvnc           ] See https://www.tigervnc.org for information on TigerVNC.
[xvnc           ] Underlying X server release 12014000
[xvnc           ] Fri Dec 15 10:37:38 2023
[xvnc           ]  vncext:      VNC extension running!
[xvnc           ]  vncext:      Listening for VNC connections on /tmp/vnc.sock (mode 0660)
[xvnc           ]  vncext:      Listening for VNC connections on all interface(s), port 5900
[xvnc           ]  vncext:      created VNC server for screen 0
[supervisor     ] starting service 'openbox'...
[supervisor     ] starting service 'nginx'...
[nginx          ] Listening for HTTP connections on port 5800.
[supervisor     ] starting service 'app'...
[supervisor     ] all services started.
[supervisor     ] SIGTERM received, shutting down...
[supervisor     ] stopping service 'app'...
[supervisor     ] service 'app' exited (with status 0).
[supervisor     ] stopping service 'nginx'...
[supervisor     ] service 'nginx' exited (with status 0).
[supervisor     ] stopping service 'openbox'...
[supervisor     ] service 'openbox' exited (with status 0).
[supervisor     ] stopping service 'xvnc'...
[xvnc           ] Fri Dec 15 10:48:02 2023
[xvnc           ]  ComparingUpdateTracker: 0 pixels in / 0 pixels out
[xvnc           ]  ComparingUpdateTracker: (1:-nan ratio)
[supervisor     ] service 'xvnc' exited (with status 0).
[supervisor     ] stopping service 'CrashPlanEngine'...
[supervisor     ] stopping service 'logmonitor'...
[supervisor     ] service 'logmonitor' exited (got signal SIGTERM).
[supervisor     ] sending SIGTERM to all processes...
[supervisor     ] service 'CrashPlanEngine' exited (with status 0).
[finish      ] executing container finish scripts...
[finish      ] all container finish scripts executed.
[init        ] container is starting...
[cont-env    ] loading container environment variables...
[cont-env    ] APP_NAME: loading...
[cont-env    ] APP_VERSION: loading...
[cont-env    ] DISPLAY: executing...
[cont-env    ] DISPLAY: terminated successfully.
[cont-env    ] DISPLAY: loading...
[cont-env    ] DOCKER_IMAGE_PLATFORM: loading...
[cont-env    ] DOCKER_IMAGE_VERSION: loading...
[cont-env    ] GTK2_RC_FILES: executing...
[cont-env    ] GTK2_RC_FILES: terminated successfully.
[cont-env    ] GTK2_RC_FILES: loading...
[cont-env    ] GTK_THEME: executing...
[cont-env    ] GTK_THEME: terminated successfully.
[cont-env    ] GTK_THEME: loading...
[cont-env    ] HOME: loading...
[cont-env    ] QT_STYLE_OVERRIDE: executing...
[cont-env    ] QT_STYLE_OVERRIDE: terminated successfully.
[cont-env    ] QT_STYLE_OVERRIDE: loading...
[cont-env    ] TAKE_CONFIG_OWNERSHIP: loading...
[cont-env    ] XDG_CACHE_HOME: loading...
[cont-env    ] XDG_CONFIG_HOME: loading...
[cont-env    ] XDG_DATA_HOME: loading...
[cont-env    ] XDG_RUNTIME_DIR: loading...
[cont-env    ] XDG_STATE_HOME: loading...
[cont-env    ] container environment variables initialized.
[cont-secrets] loading container secrets...
[cont-secrets] container secrets loaded.
[cont-init   ] executing container initialization scripts...
[cont-init   ] 10-certs.sh: executing...
[cont-init   ] 10-certs.sh: terminated successfully.
[cont-init   ] 10-check-app-niceness.sh: executing...
[cont-init   ] 10-check-app-niceness.sh: terminated successfully.
[cont-init   ] 10-clean-logmonitor-states.sh: executing...
[cont-init   ] 10-clean-logmonitor-states.sh: terminated successfully.
[cont-init   ] 10-clean-tmp-dir.sh: executing...
[cont-init   ] 10-clean-tmp-dir.sh: terminated successfully.
[cont-init   ] 10-fontconfig-cache-dir.sh: executing...
[cont-init   ] 10-fontconfig-cache-dir.sh: terminated successfully.
[cont-init   ] 10-init-users.sh: executing...
[cont-init   ] 10-init-users.sh: terminated successfully.
[cont-init   ] 10-nginx.sh: executing...
[cont-init   ] 10-nginx.sh: terminated successfully.
[cont-init   ] 10-openbox.sh: executing...
[cont-init   ] 10-openbox.sh: terminated successfully.
[cont-init   ] 10-pkgs-mirror.sh: executing...
[cont-init   ] 10-pkgs-mirror.sh: terminated successfully.
[cont-init   ] 10-set-tmp-dir-perms.sh: executing...
[cont-init   ] 10-set-tmp-dir-perms.sh: terminated successfully.
[cont-init   ] 10-vnc-password.sh: executing...
[cont-init   ] 10-vnc-password.sh: terminated successfully.
[cont-init   ] 10-web-data.sh: executing...
[cont-init   ] 10-web-data.sh: terminated successfully.
[cont-init   ] 10-x11-unix.sh: executing...
[cont-init   ] 10-x11-unix.sh: terminated successfully.
[cont-init   ] 10-xdg-runtime-dir.sh: executing...
[cont-init   ] 10-xdg-runtime-dir.sh: terminated successfully.
[cont-init   ] 15-cjk-font.sh: executing...
[cont-init   ] 15-cjk-font.sh: terminated successfully.
[cont-init   ] 15-install-pkgs.sh: executing...
[cont-init   ] 15-install-pkgs.sh: terminated successfully.
[cont-init   ] 55-crashplan-pro.sh: executing...
[cont-init   ] 55-crashplan-pro.sh: setting CrashPlan Engine maximum memory to 9162m
[cont-init   ] 55-crashplan-pro.sh: terminated successfully.
[cont-init   ] 55-validate_max_mem.sh: executing...
[cont-init   ] 55-validate_max_mem.sh: terminated successfully.
[cont-init   ] 85-take-config-ownership.sh: executing...
[cont-init   ] 85-take-config-ownership.sh: terminated successfully.
[cont-init   ] 89-info.sh: executing...
    ╭――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――╮
    │                                                                      │
    │ Application:           CrashPlan                                     │
    │ Application Version:   11.2.0                                        │
    │ Docker Image Version:  23.11.4                                       │
    │ Docker Image Platform: linux/amd64                                   │
    │                                                                      │
    ╰――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――╯
[cont-init   ] 89-info.sh: terminated successfully.
[cont-init   ] all container initialization scripts executed.
[init        ] giving control to process supervisor.
[supervisor  ] loading services...
[supervisor  ] loading service 'default'...
[supervisor  ] loading service 'logrotate'...
[supervisor  ] loading service 'logmonitor'...
[supervisor  ] loading service 'app'...
[supervisor  ] loading service 'CrashPlanEngine'...
[supervisor  ] loading service 'gui'...
[supervisor  ] loading service 'openbox'...
[supervisor  ] loading service 'xvnc'...
[supervisor  ] loading service 'certsmonitor'...
[supervisor  ] service 'certsmonitor' is disabled.
[supervisor  ] loading service 'nginx'...
[supervisor  ] all services loaded.
[supervisor     ] starting services...
[supervisor     ] starting service 'logmonitor'...
[logmonitor     ] Monitoring log file: /config/log/service.log.0
[logmonitor     ] Monitoring status file: /config/log/app.log
[supervisor     ] starting service 'CrashPlanEngine'...
[supervisor     ] starting service 'xvnc'...
[xvnc           ] Xvnc TigerVNC 1.13.1 - built Nov 17 2023 22:53:44
[xvnc           ] Copyright (C) 1999-2022 TigerVNC Team and many others (see README.rst)
[xvnc           ] See https://www.tigervnc.org for information on TigerVNC.
[xvnc           ] Underlying X server release 12014000
[xvnc           ] Fri Dec 15 10:48:57 2023
[xvnc           ]  vncext:      VNC extension running!
[xvnc           ]  vncext:      Listening for VNC connections on /tmp/vnc.sock (mode 0660)
[xvnc           ]  vncext:      Listening for VNC connections on all interface(s), port 5900
[xvnc           ]  vncext:      created VNC server for screen 0
[supervisor     ] starting service 'openbox'...
[supervisor     ] starting service 'nginx'...
[nginx          ] Listening for HTTP connections on port 5800.
[supervisor     ] starting service 'app'...
[supervisor     ] all services started.
[xvnc           ] Fri Dec 15 10:52:56 2023
[xvnc           ]  Connections: accepted: /tmp/vnc.sock
[xvnc           ]  SConnection: Client needs protocol version 3.8
[xvnc           ]  SConnection: Client requests security type None(1)
[xvnc           ]  VNCSConnST:  Server default pixel format depth 24 (32bpp) little-endian rgb888
[xvnc           ] Fri Dec 15 10:52:57 2023
[xvnc           ]  VNCSConnST:  Client pixel format depth 24 (32bpp) little-endian bgr888
[xvnc           ]  ComparingUpdateTracker: 0 pixels in / 0 pixels out
[xvnc           ]  ComparingUpdateTracker: (1:-nan ratio)
[supervisor     ] SIGTERM received, shutting down...
[supervisor     ] stopping service 'app'...
[supervisor     ] stopping service 'nginx'...
[xvnc           ] Fri Dec 15 11:06:17 2023
[xvnc           ]  VNCSConnST:  closing /tmp/vnc.sock: Clean disconnection
[xvnc           ]  EncodeManager: Framebuffer updates: 337
[xvnc           ]  EncodeManager:   Tight:
[xvnc           ]  EncodeManager:     Solid: 121 rects, 6.54884 Mpixels
[xvnc           ]  EncodeManager:            1.89062 KiB (1:13531.4 ratio)
[xvnc           ]  EncodeManager:     Bitmap RLE: 29 rects, 63.693 kpixels
[xvnc           ]  EncodeManager:                 927 B (1:275.21 ratio)
[xvnc           ]  EncodeManager:     Indexed RLE: 330 rects, 196.907 kpixels
[xvnc           ]  EncodeManager:                  28.1123 KiB (1:27.4981 ratio)
[xvnc           ]  EncodeManager:   Tight (JPEG):
[xvnc           ]  EncodeManager:     Full Colour: 191 rects, 521.278 kpixels
[xvnc           ]  EncodeManager:                  309.352 KiB (1:6.58953 ratio)
[xvnc           ]  EncodeManager:   Total: 671 rects, 7.33072 Mpixels
[xvnc           ]  EncodeManager:          340.26 KiB (1:84.1812 ratio)
[xvnc           ]  Connections: closed: /tmp/vnc.sock
[xvnc           ]  ComparingUpdateTracker: 8.14077 Mpixels in / 3.15555 Mpixels out
[xvnc           ]  ComparingUpdateTracker: (1:2.57982 ratio)
[supervisor     ] service 'nginx' exited (with status 0).
[supervisor     ] service 'app' exited (with status 0).
[supervisor     ] stopping service 'openbox'...
[supervisor     ] service 'openbox' exited (with status 0).
[supervisor     ] stopping service 'xvnc'...
[xvnc           ] Fri Dec 15 11:06:18 2023
[xvnc           ]  ComparingUpdateTracker: 0 pixels in / 0 pixels out
[xvnc           ]  ComparingUpdateTracker: (1:-nan ratio)
[supervisor     ] service 'xvnc' exited (with status 0).
[supervisor     ] stopping service 'CrashPlanEngine'...
[supervisor     ] stopping service 'logmonitor'...
[supervisor     ] service 'logmonitor' exited (got signal SIGTERM).
[supervisor     ] sending SIGTERM to all processes...
[supervisor     ] sending SIGKILL to all processes...
[supervisor     ] service 'CrashPlanEngine' exited (got signal SIGKILL).
[finish      ] executing container finish scripts...
[finish      ] all container finish scripts executed.
[init        ] container is starting...
[cont-env    ] loading container environment variables...
[cont-env    ] APP_NAME: loading...
[cont-env    ] APP_VERSION: loading...
[cont-env    ] DISPLAY: executing...
[cont-env    ] DISPLAY: terminated successfully.
[cont-env    ] DISPLAY: loading...
[cont-env    ] DOCKER_IMAGE_PLATFORM: loading...
[cont-env    ] DOCKER_IMAGE_VERSION: loading...
[cont-env    ] GTK2_RC_FILES: executing...
[cont-env    ] GTK2_RC_FILES: terminated successfully.
[cont-env    ] GTK2_RC_FILES: loading...
[cont-env    ] GTK_THEME: executing...
[cont-env    ] GTK_THEME: terminated successfully.
[cont-env    ] GTK_THEME: loading...
[cont-env    ] HOME: loading...
[cont-env    ] QT_STYLE_OVERRIDE: executing...
[cont-env    ] QT_STYLE_OVERRIDE: terminated successfully.
[cont-env    ] QT_STYLE_OVERRIDE: loading...
[cont-env    ] TAKE_CONFIG_OWNERSHIP: loading...
[cont-env    ] XDG_CACHE_HOME: loading...
[cont-env    ] XDG_CONFIG_HOME: loading...
[cont-env    ] XDG_DATA_HOME: loading...
[cont-env    ] XDG_RUNTIME_DIR: loading...
[cont-env    ] XDG_STATE_HOME: loading...
[cont-env    ] container environment variables initialized.
[cont-secrets] loading container secrets...
[cont-secrets] container secrets loaded.
[cont-init   ] executing container initialization scripts...
[cont-init   ] 10-certs.sh: executing...
[cont-init   ] 10-certs.sh: terminated successfully.
[cont-init   ] 10-check-app-niceness.sh: executing...
[cont-init   ] 10-check-app-niceness.sh: terminated successfully.
[cont-init   ] 10-clean-logmonitor-states.sh: executing...
[cont-init   ] 10-clean-logmonitor-states.sh: terminated successfully.
[cont-init   ] 10-clean-tmp-dir.sh: executing...
[cont-init   ] 10-clean-tmp-dir.sh: terminated successfully.
[cont-init   ] 10-fontconfig-cache-dir.sh: executing...
[cont-init   ] 10-fontconfig-cache-dir.sh: terminated successfully.
[cont-init   ] 10-init-users.sh: executing...
[cont-init   ] 10-init-users.sh: terminated successfully.
[cont-init   ] 10-nginx.sh: executing...
[cont-init   ] 10-nginx.sh: terminated successfully.
[cont-init   ] 10-openbox.sh: executing...
[cont-init   ] 10-openbox.sh: terminated successfully.
[cont-init   ] 10-pkgs-mirror.sh: executing...
[cont-init   ] 10-pkgs-mirror.sh: terminated successfully.
[cont-init   ] 10-set-tmp-dir-perms.sh: executing...
[cont-init   ] 10-set-tmp-dir-perms.sh: terminated successfully.
[cont-init   ] 10-vnc-password.sh: executing...
[cont-init   ] 10-vnc-password.sh: terminated successfully.
[cont-init   ] 10-web-data.sh: executing...
[cont-init   ] 10-web-data.sh: terminated successfully.
[cont-init   ] 10-x11-unix.sh: executing...
[cont-init   ] 10-x11-unix.sh: terminated successfully.
[cont-init   ] 10-xdg-runtime-dir.sh: executing...
[cont-init   ] 10-xdg-runtime-dir.sh: terminated successfully.
[cont-init   ] 15-cjk-font.sh: executing...
[cont-init   ] 15-cjk-font.sh: terminated successfully.
[cont-init   ] 15-install-pkgs.sh: executing...
[cont-init   ] 15-install-pkgs.sh: terminated successfully.
[cont-init   ] 55-crashplan-pro.sh: executing...
[cont-init   ] 55-crashplan-pro.sh: setting CrashPlan Engine maximum memory to 9162m
[cont-init   ] 55-crashplan-pro.sh: terminated successfully.
[cont-init   ] 55-validate_max_mem.sh: executing...
[cont-init   ] 55-validate_max_mem.sh: terminated successfully.
[cont-init   ] 85-take-config-ownership.sh: executing...
[cont-init   ] 85-take-config-ownership.sh: terminated successfully.
[cont-init   ] 89-info.sh: executing...
    ╭――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――╮
    │                                                                      │
    │ Application:           CrashPlan                                     │
    │ Application Version:   11.2.0                                        │
    │ Docker Image Version:  23.11.4                                       │
    │ Docker Image Platform: linux/amd64                                   │
    │                                                                      │
    ╰――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――╯
[cont-init   ] 89-info.sh: terminated successfully.
[cont-init   ] all container initialization scripts executed.
[init        ] giving control to process supervisor.
[supervisor  ] loading services...
[supervisor  ] loading service 'default'...
[supervisor  ] loading service 'logrotate'...
[supervisor  ] loading service 'logmonitor'...
[supervisor  ] loading service 'app'...
[supervisor  ] loading service 'CrashPlanEngine'...
[supervisor  ] loading service 'gui'...
[supervisor  ] loading service 'openbox'...
[supervisor  ] loading service 'xvnc'...
[supervisor  ] loading service 'certsmonitor'...
[supervisor  ] service 'certsmonitor' is disabled.
[supervisor  ] loading service 'nginx'...
[supervisor  ] all services loaded.
[supervisor     ] starting services...
[supervisor     ] starting service 'logmonitor'...
[logmonitor     ] Monitoring log file: /config/log/service.log.0
[logmonitor     ] Monitoring status file: /config/log/app.log
[supervisor     ] starting service 'CrashPlanEngine'...
[supervisor     ] starting service 'xvnc'...
[xvnc           ] Xvnc TigerVNC 1.13.1 - built Nov 17 2023 22:53:44
[xvnc           ] Copyright (C) 1999-2022 TigerVNC Team and many others (see README.rst)
[xvnc           ] See https://www.tigervnc.org for information on TigerVNC.
[xvnc           ] Underlying X server release 12014000
[xvnc           ] Fri Dec 15 11:07:12 2023
[xvnc           ]  vncext:      VNC extension running!
[xvnc           ]  vncext:      Listening for VNC connections on /tmp/vnc.sock (mode 0660)
[xvnc           ]  vncext:      Listening for VNC connections on all interface(s), port 5900
[xvnc           ]  vncext:      created VNC server for screen 0
[supervisor     ] starting service 'openbox'...
[supervisor     ] starting service 'nginx'...
[nginx          ] Listening for HTTP connections on port 5800.
[supervisor     ] starting service 'app'...
[supervisor     ] all services started.
[xvnc           ] Fri Dec 15 11:07:56 2023
[xvnc           ]  Connections: accepted: /tmp/vnc.sock
[xvnc           ]  SConnection: Client needs protocol version 3.8
[xvnc           ]  SConnection: Client requests security type None(1)
[xvnc           ]  VNCSConnST:  Server default pixel format depth 24 (32bpp) little-endian rgb888
[xvnc           ]  VNCSConnST:  Client pixel format depth 24 (32bpp) little-endian bgr888
[xvnc           ]  ComparingUpdateTracker: 0 pixels in / 0 pixels out
[xvnc           ]  ComparingUpdateTracker: (1:-nan ratio)
[xvnc           ] Fri Dec 15 11:22:06 2023
[xvnc           ]  VNCSConnST:  closing /tmp/vnc.sock: Clean disconnection
[xvnc           ]  EncodeManager: Framebuffer updates: 425
[xvnc           ]  EncodeManager:   Tight:
[xvnc           ]  EncodeManager:     Solid: 158 rects, 4.27299 Mpixels
[xvnc           ]  EncodeManager:            2.46875 KiB (1:6761.82 ratio)
[xvnc           ]  EncodeManager:     Bitmap RLE: 33 rects, 64.816 kpixels
[xvnc           ]  EncodeManager:                 1.03613 KiB (1:244.731 ratio)
[xvnc           ]  EncodeManager:     Indexed RLE: 387 rects, 228.048 kpixels
[xvnc           ]  EncodeManager:                  32.1191 KiB (1:27.8758 ratio)
[xvnc           ]  EncodeManager:   Tight (JPEG):
[xvnc           ]  EncodeManager:     Full Colour: 269 rects, 728.889 kpixels
[xvnc           ]  EncodeManager:                  408.757 KiB (1:6.97328 ratio)
[xvnc           ]  EncodeManager:   Total: 847 rects, 5.29475 Mpixels
[xvnc           ]  EncodeManager:          444.381 KiB (1:46.5649 ratio)
[xvnc           ]  Connections: closed: /tmp/vnc.sock
[xvnc           ]  ComparingUpdateTracker: 7.82356 Mpixels in / 1.13732 Mpixels out
[xvnc           ]  ComparingUpdateTracker: (1:6.87893 ratio)``

**Comment by LeeTaylorX12** [comment]
docker inspect
[
    {
        "Id": "d5f2e57a889a813091b59242695cb847dfa25eea258ea35e0f73a04580cc4a35",
        "Created": "2023-12-15T08:49:35.119101622Z",
        "Path": "/init",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 923,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2023-12-15T11:07:05.945213972Z",
            "FinishedAt": "2023-12-15T11:06:24.287451077Z"
        },
        "Image": "sha256:11d97681d532db6b87d9fbafa77fe401801ead209e448315c01ae839875dcfb3",
        "ResolvConfPath": "/var/lib/docker/containers/d5f2e57a889a813091b59242695cb847dfa25eea258ea35e0f73a04580cc4a35/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/d5f2e57a889a813091b59242695cb847dfa25eea258ea35e0f73a04580cc4a35/hostname",
        "HostsPath": "/var/lib/docker/containers/d5f2e57a889a813091b59242695cb847dfa25eea258ea35e0f73a04580cc4a35/hosts",
        "LogPath": "/var/lib/docker/containers/d5f2e57a889a813091b59242695cb847dfa25eea258ea35e0f73a04580cc4a35/d5f2e57a889a813091b59242695cb847dfa25eea258ea35e0f73a04580cc4a35-json.log",
        "Name": "/crashplanPro4",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": [
            "d4ebb0f4e62dd93911dd70fefa73e8799e9faa3bea9a4c1112a9a69ca862fdd2"
        ],
        "HostConfig": {
            "Binds": [
                "/mnt/media:/PlexMedia:rw",
                "/mnt/backup:/backup:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "crashplan-pro4_default",
            "PortBindings": {
                "5800/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "5800"
                    }
                ],
                "5900/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "5900"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "ConsoleSize": [
                0,
                0
            ],
            "CapAdd": null,
            "CapDrop": null,
            "CgroupnsMode": "private",
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": [],
            "GroupAdd": null,
            "IpcMode": "private",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": null,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "Mounts": [
                {
                    "Type": "volume",
                    "Source": "crashplan-pro4_crashplanConfig4",
                    "Target": "/config",
                    "VolumeOptions": {}
                }
            ],
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware",
                "/sys/devices/virtual/powercap"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/a69ee45424a459742521d3e6e4c6399cb76384dae1b25087949f4c3bb2094cdb-init/diff:/var/lib/docker/overlay2/43e84e21fe6f380025095ca209ab3c9130dc189ba0736c26a86bfb8e906a8bf3/diff:/var/lib/docker/overlay2/32a65abe7364c34d643d1aa0ae71377bcc1bcb2bf00575ddd37ced219e3d0787/diff:/var/lib/docker/overlay2/a360f802c0c3203e39c73f73bca4b9d108dfe0678ea643b18675d5d55ca87f62/diff:/var/lib/docker/overlay2/4045ebb1303b34744654fc6e8a86bf8f8d63b05fce09603f2151500c3b626734/diff:/var/lib/docker/overlay2/baf4dbf2ef4334fa03eafe149b7721711327e19601a5c62a36062926c4813646/diff:/var/lib/docker/overlay2/d17c93d78ee7452f72694f425fe0cbbb74e92b3d0219cf0577637b786e54fc73/diff:/var/lib/docker/overlay2/97519d21e3dec32842f5ba222902b701289d9ade520c9b978d16a7c576bd8d19/diff:/var/lib/docker/overlay2/3172926bb9399e9ce158714c0096edb85dc37eaa4286287a95806da31696cc61/diff:/var/lib/docker/overlay2/0d0e5fc665a08246d9d694dc5e7f23ae6195b5aa8cf931168cfef5bd7f80fd9d/diff:/var/lib/docker/overlay2/3711f5e78b059b6dd2bf66578b50f18937e4de33474d0939db3e5fc7df8a05f6/diff:/var/lib/docker/overlay2/d65291251f8ab9964758474a3e42368318d645f991228ca12d92d25b366c88c9/diff:/var/lib/docker/overlay2/975a0c6d850524c1ec413cd382f4bb465fdd76dc95be0aa5c873c03ef87521c6/diff:/var/lib/docker/overlay2/ab7547832860bba93b09a7eea8cd031190080b497578068f5aee7d0479b60447/diff:/var/lib/docker/overlay2/98c11dd48004bfd2cce4ef7185aa7dc03bc40a26fdcc8c0fd6d528f514e810b7/diff:/var/lib/docker/overlay2/f39d88f592fc6aeda58da67b1c9acb0188ac92adc6ce9e9c9ffe79b33ad3751d/diff:/var/lib/docker/overlay2/9687b0259c400998a9a51e715ec4d54cefe71937bf08e027c018e46561d8bd4f/diff:/var/lib/docker/overlay2/da414cf437c9039ba5e0fe2f7e491d27d956ef9bd62a19acc637361d64e025f6/diff:/var/lib/docker/overlay2/b524b75611fd86bfc1524c6ca71260fe1165d4fde0e4af202f10b0121579c05d/diff:/var/lib/docker/overlay2/714345323a82d65ee3eb25829531c89affe90a7a832fbf0f00be7d4a8ef54147/diff:/var/lib/docker/overlay2/9d1c8fc09c50290ac98f5379bae72ff9f93706ce996222b4c627d54bf0cd1b04/diff:/var/lib/docker/overlay2/8b6ea900eee8630fd55119518a944713e6112dc48169bbe91d9d3359305fe5bd/diff:/var/lib/docker/overlay2/23bcc5b00f037c2f6ae21d51358c3d965c1ae9e93b62bfe170d62300d59f9e05/diff:/var/lib/docker/overlay2/d931b7dea9da900ccacd10b93361fb3b99cf292980c09d6c7e4068fd32dba292/diff:/var/lib/docker/overlay2/59c9bd2ad99fde239f7d0a815a912310fadfb815b8c84c356d12051875fd5164/diff:/var/lib/docker/overlay2/9c1f3833f3045babce786e9204178d00d0627e5e1626b6836979101456e03d85/diff:/var/lib/docker/overlay2/9fcbc2451905e589eb3bc245c1d7182ce97259056e82a1bcff4b28445e799238/diff:/var/lib/docker/overlay2/4ba003f838c02f9502995ffbe4ea8215a91182f4c12ef6fa65abf3d588cf6ce1/diff:/var/lib/docker/overlay2/b31bafa9d4c3f0d3ed284b55e0346b54b7a8931c37d7b1ed012de269a91b3199/diff:/var/lib/docker/overlay2/8807cdc01ce1c561ab27509982a1cac0d8bbb8d36ea219663213e178319b8786/diff:/var/lib/docker/overlay2/bf4f45c1bd5b85a11fea301b5b66363f7ae6f52d7f971b99ced4d6f8a3cb72e9/diff:/var/lib/docker/overlay2/3c526c8de236f1cff6e0aca1f64957b5095d502c69183819c07bc64ed1e12557/diff:/var/lib/docker/overlay2/6f3509ab23833a6d843436ea197a4f54cc6c5094c97c86102ab8debf6cc30a11/diff:/var/lib/docker/overlay2/5ae49901bfc9a7440c4b58d08df49d4aa8ac131fa777f619c3b266e82156f08f/diff:/var/lib/docker/overlay2/b479ef6e6458de5028b51a5eeae5c190edfbfcccfe0764866681f80f9250334f/diff:/var/lib/docker/overlay2/a8a90cf76a74d24bd80e0df1ffdea8aa4ccad70aea508a0e95d06325bf8cfb31/diff:/var/lib/docker/overlay2/d33710d615b0eb876c654e7ace1f38b7aef6d6a4cdd20a95f0ecde1e22349e7d/diff:/var/lib/docker/overlay2/975eb3ac9a062a56406c2dc3fbd00fd0525c9728b371a30b3cc2adc03be32145/diff",
                "MergedDir": "/var/lib/docker/overlay2/a69ee45424a459742521d3e6e4c6399cb76384dae1b25087949f4c3bb2094cdb/merged",
                "UpperDir": "/var/lib/docker/overlay2/a69ee45424a459742521d3e6e4c6399cb76384dae1b25087949f4c3bb2094cdb/diff",
                "WorkDir": "/var/lib/docker/overlay2/a69ee45424a459742521d3e6e4c6399cb76384dae1b25087949f4c3bb2094cdb/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/mnt/backup",
                "Destination": "/backup",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Type": "volume",
                "Name": "crashplan-pro4_crashplanConfig4",
                "Source": "/var/lib/docker/volumes/crashplan-pro4_crashplanConfig4/_data",
                "Destination": "/config",
                "Driver": "local",
                "Mode": "z",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "volume",
                "Name": "6b4cd06b33047d0f4df7490ae2a899552ffdce58f935d7404cc0fe584c9ad690",
                "Source": "/var/lib/docker/volumes/6b4cd06b33047d0f4df7490ae2a899552ffdce58f935d7404cc0fe584c9ad690/_data",
                "Destination": "/storage",
                "Driver": "local",
                "Mode": "",
                "RW": true,
                "Propagation": ""
            },
            {
                "Type": "bind",
                "Source": "/mnt/media",
                "Destination": "/PlexMedia",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "d5f2e57a889a",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": true,
            "AttachStderr": true,
            "ExposedPorts": {
                "5800/tcp": {},
                "5900/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "TZ=Europe/London",
                "PUID=1000",
                "PGID=1000",
                "CRASHPLAN_SRV_MAX_MEM=9162m",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/base/sbin:/opt/base/bin",
                "ENV=/root/.docker_rc",
                "USER_ID=1000",
                "GROUP_ID=1000",
                "SUP_GROUP_IDS=",
                "UMASK=0022",
                "LANG=en_US.UTF-8",
                "KEEP_APP_RUNNING=0",
                "APP_NICENESS=0",
                "INSTALL_PACKAGES=",
                "PACKAGES_MIRROR=",
                "CONTAINER_DEBUG=0",
                "DISPLAY_WIDTH=1920",
                "DISPLAY_HEIGHT=1080",
                "DARK_MODE=0",
                "SECURE_CONNECTION=0",
                "SECURE_CONNECTION_VNC_METHOD=SSL",
                "SECURE_CONNECTION_CERTS_CHECK_INTERVAL=60",
                "WEB_LISTENING_PORT=5800",
                "VNC_LISTENING_PORT=5900",
                "VNC_PASSWORD=",
                "ENABLE_CJK_FONT=0",
                "CRASHPLAN_SERVER_ADDRESS="
            ],
            "Cmd": [
                "/init"
            ],
            "Image": "jlesage/crashplan-pro",
            "Volumes": {
                "/config": {},
                "/storage": {}
            },
            "WorkingDir": "/tmp",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "dc1af5af68ee334021a17ec806380eb802878f99da1b9781fe5a112106f04723",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.depends_on": "",
                "com.docker.compose.image": "sha256:11d97681d532db6b87d9fbafa77fe401801ead209e448315c01ae839875dcfb3",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "crashplan-pro4",
                "com.docker.compose.project.config_files": "/data/compose/174/docker-compose.yml",
                "com.docker.compose.project.working_dir": "/data/compose/174",
                "com.docker.compose.service": "crashplan-pro",
                "com.docker.compose.version": "2.20.2",
                "org.label-schema.description": "Docker container for CrashPlan",
                "org.label-schema.name": "crashplan-pro",
                "org.label-schema.schema-version": "1.0",
                "org.label-schema.vcs-url": "https://github.com/jlesage/docker-crashplan-pro",
                "org.label-schema.version": "23.11.4"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "30187f28715571442023597626fce6c8f36c3594b3f0180498f59664a9e000e6",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "5800/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "5800"
                    },
                    {
                        "HostIp": "::",
                        "HostPort": "5800"
                    }
                ],
                "5900/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "5900"
                    },
                    {
                        "HostIp": "::",
                        "HostPort": "5900"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/30187f287155",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "crashplan-pro4_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "crashplanPro4",
                        "crashplan-pro",
                        "d5f2e57a889a"
                    ],
                    "NetworkID": "d4614cb629eb9830c15b7703b0b2cb44e5b5707fe0992145d1283048697efa75",
                    "EndpointID": "6bfa5b13c9ca3a119b2b6e260ca2cf8278289c8e2aeaa2e05c63d81f96ba4718",
                    "Gateway": "172.26.0.1",
                    "IPAddress": "172.26.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:1a:00:02",
                    "DriverOpts": null
                }
            }
        }
    }
]
``

**Comment by jlesage** [comment]
And `docker exec <container name> cat /config/conf/default.service.xml` ?

**Comment by LeeTaylorX12** [comment]
default.service.xml
`<?xml version="1.0" encoding="UTF-8"?>
<config id="service" version="13">
        <orgType>ENTERPRISE</orgType>
        <servicePeerConfig>
                <authority hideAddress="false" lockAddress="false" />
        </servicePeerConfig>
        <serviceBackupConfig>
                <backupConfig>
                        <manifestPath>/usr/local/crashplan/manifest</manifestPath>
                        <backupSets>
                                <backupSet id="1" />
                        </backupSets>
                </backupConfig>
        </serviceBackupConfig>
        <serviceUIConfig>
                <serviceHost>127.0.0.1</serviceHost>
        </serviceUIConfig>
</config>`

**Comment by jlesage** [comment]
In CrashPlan, did you have to enter a server address ?  It looks like you entered `SMB` there ?

Is your are using the Small Business plan, you need to set the `CRASHPLAN_SERVER_ADDRESS` environment variable to `SMB`.  Once this is done, CrashPlan will not ask for a server address during the login.

**Comment by abaum26** [comment]
I have the same problem. The environment variable CRASHPLAN_SERVER_ADDRESS is set to SMB.

In the web client under Server Address it says SMB:XXXX (X for a number). When I try to log in, the message "Unable to sign in. Can't connect to server."

Many thanks for the image and for your help!

**Comment by jlesage** [comment]
Did you enter `SMB` at some point as the server address in CrashPlan login screen ?

Can your share the output of `docker exec <container name> cat /config/conf/default.service.xml` ?

**Comment by jlesage** [comment]
You can try the latest image, it should fix this misconfiguration.

**Comment by abaum26** [comment]
Thanks for the tip! That was exactly the problem. I reset the container on my Synology and now the server query no longer appears. Now I can see all the backup sets again.

While I'm at it, thanks for this Docker image.

**Comment by jlesage** [comment]
Thanks for the update.

@LeeTaylorX12, were you able to fix your issue as well ?

**Comment by Megabit3000** [comment]
Hi @jlesage,

I updated to the latest crashplan image on my Synology. The update went fine, but logging in doe not work. The login screen first asks username and server address. I enter my crashplan account's username and use clients.us2.crashplanpro.com as the server address. It then asks me for my password. I enter the password, but then it says it can't log in.
The CRASHPLAN_SERVER_ADDRESS variable is empty as far as I can see. But this should not matter if I understand the above comments correctly.
If the server address must be set, how exactly do I do this? Which file to change etc??

**Comment by jlesage** [comment]
Are you using the Small Business plan ? If yes, then the `CRASHPLAN_SERVER_ADDRESS` variable should be set to `SMB`.  With this, no server address should be asked during login (like before).

**Comment by Megabit3000** [comment]
Hi @jlesage, thanks for your answer. 
I am indeed using the SMB plan. Where (and how) must the variable be set to make it become active each time after crashplan was stopped (e.g. after installing a new version)?

**Comment by planbggmbh** [comment]
1. stop the container
2. reset the container (to avoid similar problems as I had)
3. edit the container
4. in the window that opens, go to Advanced settings (I have a German interface, this may be different for you)
5. in the advanced settings look for the variable CRASHPLAN_SERVER_ADDRESS and enter SMB on the right side
6 you may have to delete two or three optional variables if the environment variables cannot be saved
7. save the environment variables
8. restart the container

The problem should now be solved.

**Comment by jlesage** [comment]
@Megabit3000, not that you also not using the latest container image.

**Comment by Megabit3000** [comment]
@planbggmbh , @jlesage ,
thank you both for your replies. It's working now.
I ended up downloading explicitly v23.12.1 (instead of 'latest'). Jocelyn, the comment that the version was not correct made the penny/eurocent drop! 
I'm following the exact same procedure as planbggmbh described. I must have messed up the update somewhere along the route - maybe I forgot to reset the container - I don't know. Glad it's solved now!

Tx for the comment planbggmbh. Keep up the superb work, Jocelyn!

**Comment by rmarchant** [comment]
I'm having this issue with the latest release.

```
    │ Application:           CrashPlan                                     │
    │ Application Version:   11.2.1                                        │
    │ Docker Image Version:  24.01.1                                       │
    │ Docker Image Platform: linux/amd64 
```

`CRASHPLAN_SERVER_ADDRESS=SMB` is set in the environment section of the `docker-compose.yml`

```
$ sudo docker exec -it crashplan sh
/tmp # echo $CRASHPLAN_SERVER_ADDRESS
SMB
```

When I navigate to the login page, the server address field still shows, and gets auto-populate with `SMB:4287`

**Comment by rmarchant** [comment]
I downgraded to `23.12.1`, but the issued persisted.

**Comment by jlesage** [comment]
> When I navigate to the login page, the server address field still shows, and gets auto-populate with SMB:4287

This looks wrong. Can you please share the container's log (`docker logs <container name>`)?

**Comment by rmarchant** [comment]
Thanks for taking a look. Here's the container's log:

```
[init        ] container is starting...
[cont-env    ] loading container environment variables...
[cont-env    ] APP_NAME: loading...
[cont-env    ] APP_VERSION: loading...
[cont-env    ] DISPLAY: executing...
[cont-env    ] DISPLAY: terminated successfully.
[cont-env    ] DISPLAY: loading...
[cont-env    ] DOCKER_IMAGE_PLATFORM: loading...
[cont-env    ] DOCKER_IMAGE_VERSION: loading...
[cont-env    ] GTK2_RC_FILES: executing...
[cont-env    ] GTK2_RC_FILES: terminated successfully.
[cont-env    ] GTK2_RC_FILES: loading...
[cont-env    ] GTK_THEME: executing...
[cont-env    ] GTK_THEME: terminated successfully.
[cont-env    ] GTK_THEME: loading...
[cont-env    ] HOME: loading...
[cont-env    ] QT_STYLE_OVERRIDE: executing...
[cont-env    ] QT_STYLE_OVERRIDE: terminated successfully.
[cont-env    ] QT_STYLE_OVERRIDE: loading...
[cont-env    ] TAKE_CONFIG_OWNERSHIP: loading...
[cont-env    ] XDG_CACHE_HOME: loading...
[cont-env    ] XDG_CONFIG_HOME: loading...
[cont-env    ] XDG_DATA_HOME: loading...
[cont-env    ] XDG_RUNTIME_DIR: loading...
[cont-env    ] XDG_STATE_HOME: loading...
[cont-env    ] container environment variables initialized.
[cont-secrets] loading container secrets...
[cont-secrets] container secrets loaded.
[cont-init   ] executing container initialization scripts...
[cont-init   ] 10-certs.sh: executing...
[cont-init   ] 10-certs.sh: terminated successfully.
[cont-init   ] 10-check-app-niceness.sh: executing...
[cont-init   ] 10-check-app-niceness.sh: terminated successfully.
[cont-init   ] 10-clean-logmonitor-states.sh: executing...
[cont-init   ] 10-clean-logmonitor-states.sh: terminated successfully.
[cont-init   ] 10-clean-tmp-dir.sh: executing...
[cont-init   ] 10-clean-tmp-dir.sh: terminated successfully.
[cont-init   ] 10-fontconfig-cache-dir.sh: executing...
[cont-init   ] 10-fontconfig-cache-dir.sh: terminated successfully.
[cont-init   ] 10-init-users.sh: executing...
[cont-init   ] 10-init-users.sh: terminated successfully.
[cont-init   ] 10-nginx.sh: executing...
[cont-init   ] 10-nginx.sh: terminated successfully.
[cont-init   ] 10-openbox.sh: executing...
[cont-init   ] 10-openbox.sh: terminated successfully.
[cont-init   ] 10-pkgs-mirror.sh: executing...
[cont-init   ] 10-pkgs-mirror.sh: terminated successfully.
[cont-init   ] 10-set-tmp-dir-perms.sh: executing...
[cont-init   ] 10-set-tmp-dir-perms.sh: terminated successfully.
[cont-init   ] 10-vnc-password.sh: executing...
[cont-init   ] 10-vnc-password.sh: terminated successfully.
[cont-init   ] 10-web-data.sh: executing...
[cont-init   ] 10-web-data.sh: terminated successfully.
[cont-init   ] 10-x11-unix.sh: executing...
[cont-init   ] 10-x11-unix.sh: terminated successfully.
[cont-init   ] 10-xdg-runtime-dir.sh: executing...
[cont-init   ] 10-xdg-runtime-dir.sh: terminated successfully.
[cont-init   ] 15-cjk-font.sh: executing...
[cont-init   ] 15-cjk-font.sh: terminated successfully.
[cont-init   ] 15-install-pkgs.sh: executing...
[cont-init   ] 15-install-pkgs.sh: terminated successfully.
[cont-init   ] 55-crashplan-pro.sh: executing...
[cont-init   ] 55-crashplan-pro.sh: handling upgrade from CrashPlan version 11.2.0 to 11.2.1...
[cont-init   ] 55-crashplan-pro.sh: running the CrashPlan for Small Business version
[cont-init   ] 55-crashplan-pro.sh: setting CrashPlan Engine maximum memory to 2048m
[cont-init   ] 55-crashplan-pro.sh: terminated successfully.
[cont-init   ] 55-validate_max_mem.sh: executing...
[cont-init   ] 55-validate_max_mem.sh: terminated successfully.
[cont-init   ] 85-take-config-ownership.sh: executing...
[cont-init   ] 85-take-config-ownership.sh: terminated successfully.
[cont-init   ] 89-info.sh: executing...
    ╭――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――╮
    │                                                                      │
    │ Application:           CrashPlan                                     │
    │ Application Version:   11.2.1                                        │
    │ Docker Image Version:  24.01.1                                       │
    │ Docker Image Platform: linux/amd64                                   │
    │                                                                      │
    ╰――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――╯
[cont-init   ] 89-info.sh: terminated successfully.
[cont-init   ] all container initialization scripts executed.
[init        ] giving control to process supervisor.
[supervisor  ] loading services...
[supervisor  ] loading service 'default'...
[supervisor  ] loading service 'logmonitor'...
[supervisor  ] loading service 'logrotate'...
[supervisor  ] loading service 'app'...
[supervisor  ] loading service 'CrashPlanEngine'...
[supervisor  ] loading service 'gui'...
[supervisor  ] loading service 'nginx'...
[supervisor  ] loading service 'xvnc'...
[supervisor  ] loading service 'certsmonitor'...
[supervisor  ] service 'certsmonitor' is disabled.
[supervisor  ] loading service 'openbox'...
[supervisor  ] all services loaded.
[supervisor     ] starting services...
[supervisor     ] starting service 'logmonitor'...
[logmonitor     ] Monitoring log file: /config/log/service.log.0
[logmonitor     ] Monitoring status file: /config/log/app.log
[supervisor     ] starting service 'CrashPlanEngine'...
[supervisor     ] starting service 'xvnc'...
[xvnc           ] Xvnc TigerVNC 1.13.1 - built Dec 21 2023 00:55:16
[xvnc           ] Copyright (C) 1999-2022 TigerVNC Team and many others (see README.rst)
[xvnc           ] See https://www.tigervnc.org for information on TigerVNC.
[xvnc           ] Underlying X server release 12014000
[xvnc           ] Mon Apr 22 14:28:20 2024
[xvnc           ]  vncext:      VNC extension running!
[xvnc           ]  vncext:      Listening for VNC connections on /tmp/vnc.sock (mode 0660)
[xvnc           ]  vncext:      Listening for VNC connections on all interface(s), port 5900
[xvnc           ]  vncext:      created VNC server for screen 0
[supervisor     ] starting service 'nginx'...
[nginx          ] Listening for HTTP connections on port 5800.
[supervisor     ] starting service 'openbox'...
[xvnc           ] Mon Apr 22 14:28:21 2024
[xvnc           ]  Connections: accepted: /tmp/vnc.sock
[supervisor     ] starting service 'app'...
[xvnc           ]  SConnection: Client needs protocol version 3.8
[xvnc           ]  SConnection: Client requests security type None(1)
[xvnc           ]  VNCSConnST:  Server default pixel format depth 24 (32bpp) little-endian rgb888
[xvnc           ]  VNCSConnST:  Client pixel format depth 24 (32bpp) little-endian bgr888
[xvnc           ]  ComparingUpdateTracker: 0 pixels in / 0 pixels out
[xvnc           ]  ComparingUpdateTracker: (1:-nan ratio)
[supervisor     ] all services started.
```

**Comment by dinkelk** [comment]
> v23.12.1

I had this problem. I resolved it by deleting all the data in the shared volume, ie. this in my docker compose:

```
    volumes:
      - "./data:/config:rw"
```

Forcing the a rebuild of the container with no data in the shared volume allowed me to log in.

**Comment by rmarchant** [comment]
@dinkelk Appreciate the tip. That worked for me too. Cheers!
